### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by ExPeacer** [kelyvin/Google-Allo-For-Desktop#12]
It would be great if we can disable or modify keyboard commands. In Hungarian, if I use an ANSI keylayout keyboard, and want to type an _í_, I need to press AltGr + J - this command opens the file sending dialog too. It's very annoying...

**Comment by kelyvin** [comment]
Because this is simply an electron app around the existing Google Allo web app (https://allo.google.com/web), the responsibility of enabling/disabling keyboard shortcuts should, by default, be handled by the corresponding app. Sorry that I can't help you there.
