### ISSUE TITLE
Google Assistant not working in the linux client.

### ISSUE THREAD

**Issue by OptimusPrimeRib77** [kelyvin/Google-Allo-For-Desktop#13]
"Talking" to the assistant in private chat never returns a result, even though the "read" icon says the message was received.

Trying to use the assistant in a chat with a real user, the "share" button is missing, and also there is no reply. Also, once I try to use the assistant in a the client, it hangs the chat in the official Android client until I delete the chat and start a new one.

**Comment by kelyvin** [comment]
Hi @OptimusPrimeRib77,

This project is simply a wrapper around Google Allo's web client (https://allo.google.com/web) that leverages electron to provide hooks into your operating system's notification system. Any specific issues with the allo experience are unforuntately outside of my control, and you can provide feedback directly to them by opening Google Allo and then following these steps: 

1. Click on your profile photo
2. Click 'Send Feedback'

Hope this helps!
