### ISSUE TITLE
On Windows, close window need to send to System tray, not close program

### ISSUE THREAD

**Issue by AdrianoCahete** [kelyvin/Google-Allo-For-Desktop#15]
It's a common user experience for desktop messengers in Windows. Instead of really close the software, the close buttons needs to send to System Tray.

Official Messenger, Telegram and WhatsApp Unofficial Desktop app does the same. Just Allo Desktop close the software.

**Comment by kelyvin** [comment]
Hi @AdrianoCahete, 

I received requests for both minimizing to the system tray and as well as removing the feature. So I have included both options in the latest release, which you can find here: 
https://github.com/kelyvin/Google-Allo-For-Desktop/releases/tag/v0.0.5

Hope this helps!
