### ISSUE TITLE
[request] Dark Theme

### ISSUE THREAD

**Issue by myspivey** [kelyvin/Google-Allo-For-Desktop#16]
Stylish has a really great dark theme for Allo, would be great to implement on the desktop side, https://userstyles.org/styles/146643/allo-dark-theme

**Comment by RogueScholar** [comment]
Seconded. Does anyone even enjoy looking at "light" themes anymore? I look at them like the horse-and-buggy: a product of their time but something best left in the past.

**Comment by kelyvin** [comment]
Hi there! 

Thanks for your patience and for the link to the dark theme. I have now included both light and dark versions in the latest release. Feel free to give them a download here: 
https://github.com/kelyvin/Google-Allo-For-Desktop/releases/tag/v0.0.5

Hope this helps!

**Comment by myspivey** [comment]
Fantastic! Thanks!
