### ISSUE TITLE
Windows 10 notifications not showing

### ISSUE THREAD

**Issue by EvanTrow** [kelyvin/Google-Allo-For-Desktop#8]
with the windows 10 Fall Creators Update 16XXX notification do not show up. I think it is related to this issue: https://github.com/electron/electron/issues/10864

Notification work on windows 15XXX.

**Comment by kelyvin** [comment]
Thanks for the heads up. Will continue to monitor and try to update the build as needed once a patch is made. Thanks!

**Comment by NeelAPatel** [comment]
Still no notifications as far as i can tell, any ideas?

**Comment by mrbmi513** [comment]
I got it working on another app by doing this...

1. adding `app.setAppUserModelId(process.execPath);` to main.js
2. Putting a shortcut to the executable in the Start Menu. My tests put it with the all users start menu shortcuts. The file paths are...
  + For all users: `C:\ProgramData\Microsoft\Windows\Start Menu`
  + For the logged-in user: `%appdata%\Microsoft\Windows\Start Menu`

This is a requirement for Windows 8/8.1 and later versions of Windows 10.

**Comment by mrbmi513** [comment]
Issue should be resolved with #18 .

**Comment by kelyvin** [comment]
Yep! Thanks to the contribution from @mrbmi513, there is now a workaround for this. I will close this for now.
